### ISSUE TITLE
frequent cron jobs and buffering master selection query result

### ISSUE THREAD

**Issue by jalbstmeijer** [maartenq/clustercron#1]
Hi,

I have a bunch of crons that need to run every minute. (12 in my case)
This means that clustercron will need to query the ELB 12 times each minute and probably queries will happen exact at the same time.

Then when you think of a 4 node cluster, the ELB will receive 48 queries each minute.

It would be nice if clustercron would be able to buffer a query result for such frequent cron jobs.
Lets say to a able to tell clustercron a query result is valid for a couple of minutes.
This would bring down the 48  queries to 4 per minute in my example.

Drawback is of course the you might miss a new master selection, but in my case this is less relevant for these frequent cron jobs.

Gr, J

**Comment by maartenq** [comment]
Feature added in version 0.4.0
